name: Build Pull Request

on: pull_request

env:
    PLUGIN_NAME: obsidian-soundscapes
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "20.x"
            - name: Build
              id: build
              run: |
                  npm ci
                  npm run build
